---
###############################################################################
# Firefly Core Install
###############################################################################
# Install core dependencies required for Firefly III install.
#
# Reference:
# * https://computingforgeeks.com/how-to-install-php-on-debian-linux/

- ansible.builtin.include_tasks: manage_users.yml

- name: 'core | get latest release version metadata'
  ansible.builtin.uri:
    url: 'https://api.github.com/repos/firefly-iii/firefly-iii/releases/latest'
    return_content: true
  register: _firefly_remote_metadata

- name: 'core | set release information'
  ansible.builtin.set_fact:
    _firefly_target_version: '{% if (firefly_version|length == 0 or firefly_version == "latest") %}{{ _firefly_remote_metadata.json.tag_name }}{% else %}{{ firefly_version }}{% endif %}'

- name: 'core | set install location'
  ansible.builtin.set_fact:
    _firefly_versioned_install_dir: '/var/www/html/firefly-iii-{{ _firefly_target_version }}'
    _firefly_install_dir:           '/var/www/html/firefly-iii'

- name: 'core | install core packages'
  ansible.builtin.apt:
    name:         '{{ firefly_default_packages }}'
    state:        'latest'
    update_cache: true

- name: 'core | add php repo key'
  ansible.builtin.apt_key:
    url:   'https://packages.sury.org/php/apt.gpg'
    state: 'present'

- name: 'core | add php repo'
  ansible.builtin.apt_repository:
    repo:     'deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main'
    filename: 'php'
    state:    'present'
    update_cache: true

- name: 'core | add packages (may take a while)'
  ansible.builtin.debug:
    msg: |
      Packages are being installed. This will take a few minutes.

- name: 'core | install php packages'
  ansible.builtin.apt:
    name:         '{{ firefly_default_php_packages }}'
    state:        'latest'
    update_cache: true

- name: 'core | set 512M php memory limit'
  ansible.builtin.lineinfile:
    path:   '/etc/php/{{ firefly_php_version }}/fpm/php.ini'
    regexp: '^memory_limit = '
    line:   'memory_limit = 512M'
  changed_when: false
