---
###############################################################################
# Configure NGINX for Serving Firefly
###############################################################################

- name: 'nginx | remove nginx template page'
  ansible.builtin.file:
    path:  '/var/www/html/index.nginx-debian.html'
    state: 'absent'

- name: 'nginx | remove nginx default site config'
  ansible.builtin.file:
    path:  '/etc/nginx/sites-enabled/default'
    state: 'absent'
  notify: 'restart nginx-fpm'

- name: 'nginx | set firefly nginx config'
  ansible.builtin.template:
    src:   'firefly.conf.j2'
    dest:  '/etc/nginx/sites-enabled/firefly.conf'
    owner: 'root'
    group: 'root'
    mode:  0640
  notify: 'restart nginx-fpm'
