---
###############################################################################
# Remove Old Firefly Versions
###############################################################################
# Mounted directories are linked in the versioned install location. Symlinks
# can be safetly deleted without affecting mountpoints.
#
# Facts:
#   _firefly_target_version

- name: 'remove old | find existing installations'
  ansible.builtin.find:
    paths:     '/var/www/html'
    file_type: 'directory'
    exclude:   'firefly-iii'
    recurse:   false
  register: _firefly_existing_installs

# storage/{export,upload} symlinks deleted, source directories untouched.
- name: 'remove old | remove old versions'
  ansible.builtin.file:
    path:  '{{ item.path }}'
    state: 'absent'
  loop: '{{ _firefly_existing_installs.files }}'
  when: >
    _firefly_target_version != item.path.split("-")[-1] and
    firefly_delete_old_versions
