---
- name: 'Prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Prepare | create cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Prepare | create cache'

    - name: 'Prepare | parse test version'
      ansible.builtin.set_fact:
        test_version: '6.4.4'

    - name: 'Prepare | check cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: '{{ "Prepare | cache " ~ test_version }}'
        test_dest: '{{ "FireflyIII-v" ~ test_version ~ item }}'
        test_url: '{{
            "https://github.com/firefly-iii/firefly-iii/releases/download/" ~
            "v" ~ test_version ~ "/" ~
            "FireflyIII-v" ~ test_version ~ item
          }}'
        test_mode: '0640'
      loop:
        - '.tar.gz'
        - '.tar.gz.asc'
        - '.tar.gz.sha256'

- name: 'Prepare'
  hosts: 'firefly-debian-13-user_data'
  gather_facts: false
  tasks:
    - name: 'Prepare | simulate user media restriction'
      ansible.builtin.file:
        path: '/data'
        owner: 33
        group: 33
        mode: '0755'
        state: 'directory'
