---
###############################################################################
# Currency
###############################################################################

# Enable exchange rate conversion? Default: False.
firefly_cfg_currency_enable_exchange_rates: false

# Enable external exchange rates?
#
# Download currency exchange rates from azure storage container hosted by
# Firefly. Not all currencies may be available. Rates may be wrong.
#
# Default: False.
firefly_cfg_currency_enable_external_rates: false
